import type { DamageReport } from '@/shared/types/damage-report'

export const demoDamageReports: DamageReport[] = [
  {
    id: 'd1',
    zoneId: '1',
    type: 'fire',
    severity: 'high',
    status: 'reported',
    lat: 36.45,
    lng: 2.88,
    description: 'Wildfire damaged 200+ newly planted saplings in northern section.',
    reportedBy: 'volunteer-001',
    reportedAt: '2026-05-15T10:30:00Z',
  },
  {
    id: 'd2',
    zoneId: '7',
    type: 'drought',
    severity: 'critical',
    status: 'verified',
    lat: 23.3,
    lng: 5.65,
    description: 'Extended drought killing acacia seedlings. Irrigation needed urgently.',
    reportedBy: 'volunteer-003',
    reportedAt: '2026-05-12T14:00:00Z',
  },
  {
    id: 'd3',
    zoneId: '8',
    type: 'vandalism',
    severity: 'medium',
    status: 'reported',
    lat: 36.46,
    lng: 6.27,
    description: 'Several olive trees uprooted near main access road.',
    reportedBy: 'volunteer-007',
    reportedAt: '2026-05-17T08:15:00Z',
  },
]
