set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g history-limit 50000

bind -n M-Left select-window -t :-
bind -n M-Right select-window -t :+

bind -n M-S-Left select-pane -L
bind -n M-S-Right select-pane -R
bind -n M-S-Up select-pane -U
bind -n M-S-Down select-pane -D

bind | split-window -h
bind - split-window -v

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g status-bg colour235
set -g status-fg white
set -g status-left ' [#S] '
set -g status-right ' %Y-%m-%d %H:%M '
set -g window-status-current-style fg=brightblue,bg=colour235,bold
