services:
  - type: web
    name: green-algeria-map
    runtime: node
    repo: https://github.com/samir1498/green-algeria-map
    branch: main
    rootDir: backend-nestjs
    buildCommand: NODE_ENV=development pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: CLIENT_URL
        value: https://green-algeria-map.pages.dev
      - key: BETTER_AUTH_URL
        value: https://green-algeria-map.onrender.com
      - key: DB_HOST
        value: db.pkzhfqfgonqsixhnxlbz.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: postgres
      - key: DATABASE_URL
        sync: false
