FROM debian:bookworm-slim
RUN apt-get update -qq && apt-get install -y -qq libz1 ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY target/backend-springboot-native app
EXPOSE 8081
CMD ["./app"]
