ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE accounts ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE accounts ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE damage_reports ADD CONSTRAINT fk_damage_reports_zone FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE;
