import type { Zone } from '@/shared/types/zone'

export const demoZones: Zone[] = [
  {
    id: '1',
    name: 'Chrea National Park',
    type: 'planting',
    status: 'in-progress',
    lat: 36.4424,
    lng: 2.8695,
    targetCount: 5000,
    currentCount: 1200,
    description: 'Reforestation of cedar forests destroyed by wildfires.',
  },
  {
    id: '2',
    name: 'Tlemcen National Park',
    type: 'planting',
    status: 'planned',
    lat: 34.8386,
    lng: -1.2939,
    targetCount: 3000,
    currentCount: 0,
    description: 'Restoring Mediterranean pine and oak ecosystems.',
  },
  {
    id: '3',
    name: 'El Kala National Park',
    type: 'planting',
    status: 'completed',
    lat: 36.8794,
    lng: 8.4389,
    targetCount: 8000,
    currentCount: 8000,
    description: 'Completed cork oak and wetland reforestation.',
  },
  {
    id: '4',
    name: 'Bejaia Coast Cleanup',
    type: 'trash',
    status: 'in-progress',
    lat: 36.7509,
    lng: 5.0859,
    description: 'Beach and coastal trash collection point.',
  },
  {
    id: '5',
    name: 'Oran Bay Cleanup',
    type: 'trash',
    status: 'planned',
    lat: 35.7043,
    lng: -0.6401,
    description: 'Organized cleanup of Oran coastline.',
  },
  {
    id: '6',
    name: 'Djurdjura Cleanup',
    type: 'cleanup',
    status: 'in-progress',
    lat: 36.4333,
    lng: 4.25,
    description: 'Mountain trail cleanup and maintenance.',
  },
  {
    id: '7',
    name: 'Hoggar Mountains Planting',
    type: 'planting',
    status: 'planned',
    lat: 23.2872,
    lng: 5.6358,
    targetCount: 2000,
    currentCount: 0,
    description: 'Acacia and drought-resistant tree planting in the Sahara.',
  },
  {
    id: '8',
    name: 'Mila Olive Grove',
    type: 'planting',
    status: 'in-progress',
    lat: 36.4514,
    lng: 6.2644,
    targetCount: 1500,
    currentCount: 600,
    description: 'Community olive tree planting project.',
  },
  {
    id: '9',
    name: 'Annaba Dunes Cleanup',
    type: 'trash',
    status: 'completed',
    lat: 36.9139,
    lng: 7.7639,
    description: 'Completed dune and beach cleanup operation.',
  },
  {
    id: '10',
    name: 'Tizi Ouzou Reforestation',
    type: 'planting',
    status: 'in-progress',
    lat: 36.7167,
    lng: 4.05,
    targetCount: 4000,
    currentCount: 1500,
    description: 'Mixed oak and pine reforestation in Kabylie region.',
  },
]
