name: CI Backend Spring Boot

on:
  push:
    branches: [main]
    paths: ['backend-springboot/**', '.github/workflows/ci-backend-springboot.yml']
  pull_request:
    paths: ['backend-springboot/**', '.github/workflows/ci-backend-springboot.yml']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-springboot
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-java@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          java-version: 25
          distribution: graalvm
          cache: maven
      - run: ./mvnw clean package
